import org.springframework.beans.factory.annotation.QualifierAnnotationAutowireCandidateResolver;
public class FunctionUse1979 {
public void funcUse() {
QualifierAnnotationAutowireCandidateResolver qualifierannotationautowirecandidateresolver = new QualifierAnnotationAutowireCandidateResolver();
qualifierannotationautowirecandidateresolver.setValueAnnotationType(null);
}
}