import org.springframework.beans.factory.annotation.QualifierAnnotationAutowireCandidateResolver;
public class FunctionUse1986 {
public void funcUse() {
QualifierAnnotationAutowireCandidateResolver qualifierannotationautowirecandidateresolver = new QualifierAnnotationAutowireCandidateResolver();
qualifierannotationautowirecandidateresolver.getFactoryMethodAnnotation(null,null);
}
}